web:
  build: .
  command: python app.py
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - redis
redis:
  image: redis
test:
  build: ./test
  links:
    - web
  command: python test.py
